version: 0.2

phases:
  install:
    commands:
      - pipenv install
      - docker run -d -p 3306:3306 mysql
  pre_build:
    commands:
      - pipenv run python -m unittest discover tests
      - export VIRTUAL_ENV=$(pipenv --venv)
  build:
    commands:
      - pipenv run zappa update
